Feature Requests #504 and #295: Matrix Editor tools rewrite
User-visible new features and changes:
Matrix editor tools:
- The following capabilites are available in any/all tools:
  - Selecting note(s):
    - Click a note to select (replaces any previous selection).
    - Shift-click note to add to selection, or remove if already in
      selection.
    - Click-drag to select multiple notes (replaces any previous selection).
    - Shift-click-drag to add multiple notes to selection, or remove
      from selection if all notes in drag area are already in
      selection.
    - Exception: Must hold Control key in Draw tool to differentiate
      from normal note drawing.
  - Double-click to delete note(s)
    - Delete clicked note if no existing selection or note not in
      selection. Also deselects any existing selected notes.
    - Delete all notes in selection if clicked note is in selection.
  - Right-click
    - If not over note brings up menu with options to switch to
      another tool (no change from current UI), plus undo/redo (new),
      plus change active segment (new).
    - If over note brings up Event Properties dialog (no change from
      current UI). Add shift for Intrinsics dialog (also as per
      current UI).
  - Click non-active segment note to change active segment.
    Exception: Must hold Control key in Draw tool to differentiate
    from normal note drawing.
  - Temporarily switch to "alternate" tool. (See below for
    tool-to-alternate mapping.)
    - Middle-click performs a single right-click action in alternate tool.
    - CapsLock toggles (activates) alternate tool on and off. (See
      "Why CapsLock?", below.)
  - Bespoke mouse cursor icons which dynamically change depending on
    context (element under mouse).
  - Full/complete context-sensitive help for all tools.
- Alternate tools:
    Tool         Alternate
    ----         ---------
    MultiTool    Draw
    Draw         MultiTool
    Erase        Draw
    Move         Resize
    Resize       Move
    Velocity     Resize
- Tools:
  - MultiTool (formerly "Select and Edit"):
    - Move, resize, or change velocity of note depending on whether mouse
      is in middle 70%, right 15%, or left 15% of note, respectively.
    - If percussion segment (and "View -> Notes -> Show percussion
      durations" is not checked "on"), move or change velocity
      depending on whether mouse is in lower 80% or upper 20% of
      note, respectively.
    - Hold Control to duplicate note(s) before moving (unchanged from
      current UI).
    - Hold Shift while moving (normal or Control/duplicate) to
      disable snap to matrix grid (unchanged from current UI)
  - Draw tool:
    - Click to create note, drag to resize (unchanged from current
      UI).
    - Hold Shift to disable snap to matrix grid (unchanged from
      current UI).
    - Control-click on non-active segment note to disable note drawing
      and perform normal non-draw-tool change of active segment.
    - Control-click-drag when not over note to disable note drawing
      and perform normal non-draw-tool click-drag select.
    - Removed check and refusal to create notes on top of, inside, or
      overlapping existing notes. Problems with such notes creating
      pathological MIDI sequences (e.g. two Note On events without
      intervening Note Off or vice-versa, or multiple Note On/Off
      events at the same MIDI time, etc) will be handled more
      completely/globally in an upcoming merge request via
      improvements the to internal RG "commands" implementations.
   - Erase tool:
     - Click to delete single note if not in selection.
     - Delete selection if clicked note in selection.
     - Tool largely superfluous given double-click delete available
       in all tools, but convenient (single- vs double-click) if
       interactively deleting large numbers of notes not easily
       click-drag-selectable.
   - Move tool:
     - Same as MultiTool click in middle of note.
     - Largely superfluous given the above, but convenient for moving
       "small" (short duration) notes without necessitating large
       horizontal zoom size.
   - Resize tool:
     - Same as MultiTool click in rightmost 15% of note.
     - Similarly superfluous as per comments on Move tool, above.
     - Will only resize last of tied notes, and only resize those to
       right (later music time).
   - Velocity tool:
     - Same as MultiTool click in leftmost 15% of note.
     - Similarly superfluous as per comments on Move tool, above.
General tools UI:
- No change to current UI behavior that only active segment notes can
  be created/selected/modified (intentional UI/workflow design
  feature).
- Active segment changer roller retained unchanged.
- Why CapsLock?
  - The original intent was to use the Alt key for switching to
    alternate tools. This would be preferable as would not have the
    toggling behavior of CapsLock (which dilutes the "non-modal"
    intent of the new design).
  - But Qt special-cases Alt key handling (also Tab, which would have
    been a second choice).
  - All (many!) attempts at working around this limitation were
    unsuccessful. Stub code, disabled within "#if 0"/"endif" blocks
    are retained in the source for possible future work.
  - On the positive side, this creates a productive purpose for the
    otherwise useless CapsLock key.
Other new user-visible features:
- Improvement to MIDI input playback instrument handling. Now changes
  when mouse enters any part of main or editor windows, not just
  central widget area as previously.
- Main window, Control key (in addition to existing Shift) to
  add/remove tracks/segments to selection. Matches common UI
  standards. Needs further work: Shift should select range of
  tracks/segments, again as per common UI standards.
- Visual differentiation between vertical bar/beat/grid lines in
  Matrix Editor grid.
Bug fixes:
- Fix for thanks4opensource-introduced bug in PianoRuler display.
  Also complete rewrite/simplification of code including correct
  handling of arbitrary grid vertical spacing.
Code changes:
- Near-total rewrite of MatrixTool base and derived classes.
- Moved almost all tool-oriented code in MatrixWidget class to
  MatrixToolBox.
- New RosegardenDocument::signalNotesTied() and signalNotesUntied()
  methods, called from TieNotesCommand::modifySegment() and
  UntieNotesCommand::modifySegment(), which emit notesTied and
  notesUntied signals.
- Improvements to detection of when context help has changed for
  eliminating redundant calls to Qt text display.
- Several new data/pixmaps/*.png icons/cursors.
- Removal of /data/rc/matrix*.rc files, obviated by single/dynamic
  matrix editor right-click grid menu.
- Removal of src/gui/editors/matrix/MatrixSelector.{cpp,h} (code
  refactored/rewritten into MatrixSelect and MatrixMultiTool).